### PR TITLE
Unwanted stuff

### PR DESCRIPTION
**Pull request by ramico**
if approved commented code is to be deleted

### CODE REVIEW

**Comment by nabsul** [comment]
Please explain the reasoning for this change :-)

**Comment by ramico** [comment]
i don't know how to reply -where to here it is - 

all col headers are just a table header tag with text and woocomm... attribs 
and no tool-tip as well  

this would make the table inconsistent 
th

**Comment by nabsul** [comment]
I guess. I was keeping this tooltip in case one day we want to give the user extra information. But the individual buttons below also have tooltips, so I think we can remove this without losing much.

**Comment by ramico** [comment]
what buttons

**Comment by nabsul** [comment]
image

**Comment by ramico** [comment]
un
un harmed
harmed

**Pull request merged**
